name: Run Test
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: 'example/node_modules'
          key: node-${{ hashFiles('example/package-lock.json') }}
          restore-keys: node-
      - name: Setup package
        run: |
          sudo apt-get update -q
          sudo apt-get install -y libnss3 libasound2t64 libgbm-dev poppler-utils task-japanese locales-all
      - name: Setup Japanese Locale
        run: |
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Test
        run: |
          cd example/
          npm install
          npm start
